### ISSUE TITLE
Permissions Issues Since Updating to Latest

### ISSUE THREAD

**Issue by culpeppers** [jhonderson/actual-http-api#18]
Since updating to latest version, seeing these errors in the actual-http-api logs:

PostError: PostError: unauthorized
    at throwIfNot200 (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39687:31)
    at postBinary (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39753:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42602:35)
    at async /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42503:32 {
  type: 'PostError',
  reason: 'unauthorized',
  meta: undefined
}
PostError: PostError: unauthorized
    at throwIfNot200 (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39687:31)
    at postBinary (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39753:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42602:35)
    at async /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42503:32 {
  type: 'PostError',
  reason: 'unauthorized',
  meta: undefined
}
unhandledRejection Error: We had an unknown problem opening “<BUDGETID>”.
    at handlers.api/sync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29500:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Actual is on latest as well.

**Comment by jhonderson** [comment]
Hello @culpeppers , these errors are expected to happen from time to time (I am not really sure why, I am guessing some file or cache gets stuck or something). If you are running actual-http-api using docker, using the flag `--restart=on-failure` should take care of restarting the container whenever these failures happen.

Are you using docker?, if so, does this failure keep happening even after the container restarts?

I upgraded to latest (both containers) day before yesterday and it has been working for me. Initially it gave me some errors, I think it's because actual and actual-http-api needs to be upgraded at the same time, but after 1 min and 1 restart it started working again.

**Comment by culpeppers** [comment]
I'm using it on Unraid under Docker. Would I add that as an env variable, or as something else?

Thanks!

**Comment by jhonderson** [comment]
Reading few posts looks like there are extra parameters (or advanced options), where you can add the `--restart=on-failure` flag. Let me know if it works.

- https://www.reddit.com/r/unRAID/comments/10wvn9b/way_to_automatically_restart_a_stopped_container/
- https://forums.unraid.net/topic/55582-run-containers-with-restart-unless-stopped/

**Comment by culpeppers** [comment]
Sorry for the delay. Thank you for looking into that for me. Adding that did the trick, thank you!!
