### ISSUE TITLE
Using API in cron it fails

### ISSUE THREAD

**Issue by soloam** [jhonderson/actual-http-api#26]
I'm trying to use the api to sync actualbudget with the bank via cron task... if i run the command on the shell it works, but when I run it by cron I get a error:

```json
{"error":"Unknown error while interacting with Actual Api. See server logs for more information"}
```

But when I go to the log all seems ok, I even seem GoCardless pulling the data!

Do you have any idea on what could it be?

Thank you

**Comment by jbalatero** [comment]
I am getting the same error but on a different situation.

Here are my logs

```
Actual HTTP Server Listening on PORT:  5007
Unknown error while interacting with Actual Api. See server logs for more information TypeError: injected.send is not a function
    at send (/usr/src/app/node_modules/@actual-app/api/dist/methods.js:76:21)
    at Object.downloadBudget (/usr/src/app/node_modules/@actual-app/api/dist/methods.js:93:12)
    at Budget (/usr/src/app/src/v1/budget.js:19:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/src/v1/routes/index.js:10:27
Actual api client initialized successfully
Error parsing metadata: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47109:42
    at async Promise.all (index 0)
    at async handlers.get-budgets (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47104:34)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:37318:33)
Loading fresh spreadsheet
Syncing since 2024-12-03T10:45:36.868Z-0007-bcd002848d4fbaee 0 (attempt: 0)
Got messages from server 70
Error creating map from sync id to budget id SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/src/app/src/v1/budget.js:258:31
    at Array.forEach (<anonymous>)
    at refreshSincIdToBudgetIdMap (/usr/src/app/src/v1/budget.js:257:19)
    at Budget (/usr/src/app/src/v1/budget.js:21:5)
    at async /usr/src/app/src/v1/routes/index.js:10:27
Performing transaction reconciliation
Performing transaction reconciliation matching
```
